- app-cast/prd/all.xml
- app-cast/prd/android.xml
- app-cast/prd/ios.xml
> feat: change version number

- app-cast/prd/android.xml
> chore: add optional android update

- app-cast/prd/android.xml
- app-cast/prd/ios.xml
Obrigar atualização para a Versão 4.3.0 do Aplicativo.
> chore: support update v4.3.0

- app-cast/prd/android.xml
- app-cast/prd/ios.xml
Forçar atualização da Versão 4.5.1 do CAB
> Support Update v4.5.1

- app-cast/prd/android.xml
- app-cast/prd/ios.xml
> Support Update v5.0.0

- app-cast/prd/android.xml
- app-cast/prd/ios.xml
> Support Update 5.3.1

- app-cast/prd/android.xml
- app-cast/prd/ios.xml
> Support Update 5.6.1

- app-cast/prd/ios.xml
Support Update 5.7.2 somente para IOS
> feat: support update 5.7.2 for IOS Platform

- app-cast/prd/android.xml
> feat: support update for android platform

- app-cast/prd/android.xml
- app-cast/prd/ios.xml
Atualização Versão 6.4 Opcional
> feat: bump version number AZUL-43103

- app-cast/prd/android.xml
- app-cast/prd/ios.xml
AZUL-44310
- bump android and ios versions;
> build: critical upgrade - AZUL-44310

- app-cast/prd/android.xml
- app-cast/prd/ios.xml
> build: critical upgrade AZUL-48298

- app-cast/prd/android.xml
- app-cast/prd/ios.xml
> Support Update 7.4 [AZUL-49777]

- app-cast/prd/android.xml
- app-cast/prd/ios.xml
Upgrade Obrigatório para a versão 7.6
> Support Update 7.6 [AZUL-51646]

- app-cast/prd/android.xml
- app-cast/prd/ios.xml
> Support Update 7.6 [AZUL-51646] - Revert

- app-cast/prd/android.xml
- app-cast/prd/ios.xml
> build: bump patch version - AZUL-51646

- app-cast/prd/android.xml
- app-cast/prd/ios.xml
https://contaazul.atlassian.net/browse/CHAMADO-53054
> Support Update 7.6.3 [CHAMADO-53054]

- app-cast/prd/android.xml
- app-cast/prd/ios.xml
Atualização para a versão 7.8.6
> [CHAMADO-56047]build: update for 7.8.6

- app-cast/prd/android.xml
- app-cast/prd/ios.xml
Atualização obrigatório versão 7.8.8
> build: bump support update [AZUL-58390]

- app-cast/prd/android.xml
- app-cast/prd/ios.xml
Add entries for version 8.0.2 in both Android and iOS changelogs.
> [CHAMADO-57241] Update changelog for version 8.0.2

- app-cast/prd/android.xml
- app-cast/prd/ios.xml
Update the changelogs for both Android and iOS to include version 8.3.1.
> [CHAMADO-58483] Add version 8.3.1 to Android and iOS changelogs

- app-cast/prd/android.xml
- app-cast/prd/ios.xml
Include the new version entry for both Android and iOS in their respective changelogs.
> [AZUL-74138] feat: add version 9.2.0 entry to Android and iOS changelogsAdd version 9.2.0 to Android and iOS changelogs
